
defaults:
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

start_date: 2022-05-01T00:00:00
end_date: 2022-05-01T18:00:00 #2023-06-01T18:00:00

# Update to latest checkpoint:
checkpoint_path: /pfs/lustrep4/scratch/project_465001893/anemoi/experiments/breeze_lightning/transfer_learning/checkpoint/63554362654a41dea62c3fa13316352f/inference-last.ckpt

leadtimes: 12
timestep: 6h
frequency: 6h
workdir: /pfs/lustrep4/scratch/project_465001893/erslando/lightning-anemoi-training/workdir/

deterministic: True
inference_num_chunks: 1

run_name: breeze_cloudy_lightning

# Have to change this for the new dataset structure.
dataset_data:
  cutout:
  - dataset: ${hardware.paths.data}/MEPS/${hardware.files.lam_dataset}
  - dataset: ${hardware.paths.data}/ERA5/${hardware.files.global_dataset}
  adjust: all

dataset_obs:
  dataset: ${hardware.paths.data}/lightning/${hardware.files.obs_dataset}

dataset:
  zip:
    - dataset: ${dataset_data}
    - dataset: ${dataset_obs}
  adjust: ["start", "end"]


# If the user wants to release GPU cache and memory
# This option releases unused cached/memory used by torch
release_cache: False

dataloader:
  batch_size: 1
  prefetch_factor: 1
  num_workers: 1
  pin_memory: True

  read_group_size: 1 # Do not change this, not implemented properly

  predict:
    dataset: ${dataset}
    start: ${start_date}
    end: ${end_date}
    frequency: ${frequency}

  datamodule:
    _target_: anemoi.training.data.dataset.ZipDataset
    _convert_: all

hardware:
  paths:
    data: /pfs/lustrep4/scratch/project_465001893/aifs/datasets/
    workdir: /pfs/lustrep4/scratch/project_465001893/erslando/lightning-anemoi-training/workdir/
    output: /pfs/lustrep4/scratch/project_465001893/erslando/lightning-anemoi-training/inference_output/
  files: # Change these to the correct ones.
    global_dataset: aifs-od-an-oper-0001-mars-n320-2019-2023-6h-v6.zarr
    lam_dataset: aifs-meps-2.5km-2020-2024-6h-v6.zarr
    obs_dataset: breeze_lightning.zarr

  num_gpus_per_node: 8
  num_gpus_per_model: 8
  num_nodes: 1

model:
  _target_: bris.model.NetatmoPredictor
  _convert_: all


routing:
  - decoder_index: 0
    domain: 0
    outputs:
      - netcdf:
          filename_pattern: ${hardware.paths.output}/predictions/meps_pred_%Y%m%dT%HZ.nc
          variables: [2t, msl, tp]
          extra_variables:  [10si]
#      - verif:
#          filename: ${hardware.paths.output}verif/2t/netatmo_1km_dec_only_meps.nc
#          variable: 2t
#          thresholds: [0, 10, 20]
#          quantile_levels: [0.1, 0.9]
#          units: degC
#          elev_gradient: -0.0065
#          obs_sources:
#            - verif:
#                filename: /pfs/lustrep4/scratch/project_465001383/aifs/verification/202206_202305/t2m/netatmo_1km_dec_only_10kit_r4_meps.nc
  - decoder_index: 1
    domain: 0
    outputs:
      - netcdf: 
          filename_pattern: ${hardware.paths.output}predictions/lightning_pred_%Y%m%dT%HZ.nc
          variables: [thunder_count_25km]
      - verif:
          filename: ${hardware.paths.output}verif/te/lightning_100_resolution.nc
          variable: te
          thresholds: [0, 10, 20]
          quantile_levels: [0.1, 0.9]
          units: degC
          elev_gradient: 0
          obs_sources:
            - verif:
                filename: /pfs/lustrep4/scratch/project_465001383/aifs/verification/lightning/verif_lightning_obs.nc
