start_date: 2022-05-01T00:00:00
end_date: 2022-05-02T18:00:00 #2023-06-01T18:00:00
# end_date: 2022-09-15T18:00:00 #2023-06-01T18:00:00

checkpoints:
  forecaster:
    checkpoint_path: /pfs/lustrep2/scratch/project_465001893/anemoi/experiments/breeze_lightning/transfer_learning/checkpoint/16e89d3f-b8fb-47a5-b823-cf18fae35915/inference-last.ckpt
    leadtimes: 12

frequency: 6h

inference_num_chunks: 1

# workdir: /pfs/lustrep4/scratch/project_465001383/erslando/lightning-anemoi-training/workdir/
workdir: /pfs/lustrep2/scratch/project_465001893/erslando/lightning-anemoi-training/workdir/

# New dataset structure.
dataset_data:
  cutout:
  - dataset: ${hardware.paths.data}/MEPS/${hardware.files.dataset_lam}
    trim_edge: 50
    reorder: sort
  - join:
    - dataset: ${hardware.paths.data}/ERA5/${hardware.files.dataset_global_atm}
      drop: ["sdor", "slor", "cp", "u_600", "v_600", "z_600", "t_600", "q_600", "w_600"]
    - dataset: ${hardware.paths.data}/ERA5/${hardware.files.dataset_global_land}
      select: ["lcc", "mcc", "tcc", "strd", "ssrd"]
    adjust: ["start", "end"]
    reorder: sort
  min_distance_km: 0
  adjust: all
  statistics: 
    join: 
    - dataset: ${hardware.paths.data}/ERA5/aifs-ea-an-oper-0001-mars-o96-1979-2022-6h-v6.zarr
      drop: ["sdor", "slor", "cp", "u_600", "v_600", "z_600", "t_600", "q_600", "w_600"]
    - dataset: ${hardware.paths.data}/ERA5/aifs-ea-an-oper-0001-mars-o96-1979-2023-6h-v3-land.zarr
      select: ["lcc", "mcc", "tcc", "strd", "ssrd"]
    adjust: ["start", "end"]
    reorder: sort

dataset_obs:
  dataset:
    join:
      - dataset: ${hardware.paths.data}/lightning/${hardware.files.dataset_obs}
      - dataset: ${hardware.paths.data}/lightning/${hardware.files.dataset_obs_z}
    adjust: [dates]
  mask_from_dataset:
    dataset: ${hardware.paths.data}/lightning/${hardware.files.dataset_obs_mask}
    field: thunder_mask

dataset:
  zip:
    - dataset: ${dataset_data}
    - dataset: ${dataset_obs}
  adjust: ["start", "end"]

# If the user wants to release GPU cache and memory
# This option releases unused cached/memory used by torch
release_cache: False

dataloader:

  datamodule:
    _target_: bris.data.dataset.ZipDataset
    _convert_: all

hardware:
  paths:
    data: /pfs/lustrep2/scratch/project_465001893/anemoi/datasets/
    output: /pfs/lustrep2/scratch/project_465001893/erslando/lightning-anemoi-training/inference_output/
    workdir: /pfs/lustrep2/scratch/project_465001893/erslando/lightning-anemoi-training/workdir/
  files:
    dataset_lam: aifs-meps-2.5km-2020-2023-6h-v7.zarr
    dataset_global_atm: aifs-ea-an-oper-0001-mars-n320-1979-2022-6h-v6.zarr
    dataset_global_land: aifs-ea-an-oper-0001-mars-n320-1979-2023-6h-v1-land.zarr
    dataset_obs: breeze_force_o96_6h.zarr
    dataset_obs_z: lightning_z.zarr
    dataset_obs_mask: lightning_mask.zarr
    graph: breeze_lightning_cloudy.pt

  num_gpus_per_node: 8
  num_gpus_per_model: 8
  num_nodes: 4




model:
  _target_: bris.model.MultiEncDecPredictor
  _convert_: all


routing:
  - decoder_index: 0
    domain_index: 0
    outputs:
      - netcdf:
          filename_pattern: ${hardware.paths.output}/predictions/meps_pred_%Y%m%dT%HZ.nc
          variables: [2t, msl, tp]
          # extra_variables:  [10si]
      - verif:
          filename: ${hardware.paths.output}verif/2t/netatmo_1km_dec_only_meps.nc
          variable: 2t
          thresholds: [0, 10, 20]
          quantile_levels: [0.1, 0.9]
          units: degC
          elev_gradient: -0.0065
          obs_sources:
            - verif:
                filename: /pfs/lustrep4/scratch/project_465001383/aifs/verification/202206_202305/t2m/netatmo_1km_dec_only_10kit_r4_meps.nc
  - decoder_index: 1
    domain_index: 0
    outputs:
      - netcdf: 
          filename_pattern: ${hardware.paths.output}predictions/lightning_pred_%Y%m%dT%HZ.nc
          variables: [thunder_count_25km]
#      - verif:
#          filename: ${hardware.paths.output}verif/te/breeze_lightning_100_resolution_big.nc
#          variable: te
#          variable_type: logit
#          thresholds: [0.5, 1]
#          quantile_levels: [0.1, 0.9]
#          units: probability
#          elev_gradient: 0
#          obs_sources:
#            - verif:
#                filename: /pfs/lustrep4/scratch/project_465001383/aifs/verification/lightning/verif_lightning_obs.nc
